%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/alandautov/Documents/MATLAB/temp.csv
%
% Auto-generated by MATLAB on 08-Dec-2019 00:32:37

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "";

% Specify column names and types
opts.VariableNames = "temp";
opts.VariableTypes = "string";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "temp", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "temp", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("/Users/alandautov/Documents/MATLAB/temp.csv", opts);

%% Convert to output type
temp = tbl.temp;

%% Clear temporary variables
clear opts tbl